

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainBackgroundPanel;
                ref class Slider;
                ref class TextBox;
            }
        }
    }
}

namespace SwapChainBGPanel
{
    partial ref class MainPage : public Windows::UI::Xaml::Controls::SwapChainBackgroundPanel, 
        public Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^ DXSwapChainPanel;
        private: Windows::UI::Xaml::Controls::Slider^ rotationRate;
        private: Windows::UI::Xaml::Controls::TextBox^ rotationRateValue;
    };
}

